name: flutter_core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Providers/ Blocs and saved bloc state
  provider: ^6.0.0
  flutter_bloc: ^7.3.0

  # Pagination
  infinite_scroll_pagination: ^3.1.0
  shimmer: ^2.0.0

  # Logging
  logging: ^1.0.2

  # Encryption
  encrypt: ^5.0.1

  # FilePicker
  file_picker: ^4.2.7

  # ImagePicker
  image_picker: ^0.8.4+4

  # Storage
  shared_preferences: ^2.0.15

  # To launch external urls (mail, phone or other urls)
  url_launcher: ^6.1.5

  # Web view
  webview_flutter: ^3.0.4

  # Secure Storage
  flutter_secure_storage: ^6.1.0

  # generate random numbers
  uuid: ^3.0.5

  # used for injection
  get_it: ^7.2.0

  # Localization
  intl: ^0.17.0

  # flutter jailbreak and rooted detection
  flutter_jailbreak_detection: ^1.8.0

  flutter_screenutil: ^5.5.3+2

  cached_network_image: ^3.2.2

  extended_image:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
